### ISSUE TITLE
source maps env variable?

### ISSUE THREAD

**Issue by josh-m-sharpe** [ionic-zone/fastlane-plugin-ionic#33]
```
    ionic(
      team_id: options[:team_id],
      platform: 'ios',
      prod: true,
      release: true
    )
```
seems like it produces this command: 

`ionic cordova prepare ios --release --device --prod`

How do I get it to execute with: `IONIC_GENERATE_SOURCE_MAP=true` which forces ionic to generate sourcemaps.

**Comment by janpio** [comment]
That looks like an environment variable to be set, correct? So set the env variable (depending on how your operating system does that).

**Comment by josh-m-sharpe** [comment]
Fair.
