### ISSUE TITLE
Cannot find config.xml

### ISSUE THREAD

**Issue by raiden0610** [ionic-zone/fastlane-plugin-ionic#42]
Hi,
I have an issue when I try to do `fastlane android build_debug` on MacOS and on Ubuntu 18.04
The error : `No such file or directory @ rb_sysopen - config.xml`

I use the following version : 
Ionic@4.5.0 with a project based on 3.x.x
Fastlane@2.111.0
Ruby@2.5.1
fastlane-plugin-ionic@0.1.0

Is it possible to have a look on that ?

Thanks

Regards

**Comment by raiden0610** [comment]
I generate a ionic project with` ionic start myApp tabs`
Then, `cordova platform add android`
`fastlane init` in the platform/android folder
My lane is like this : 
```
default_platform(:android)
platform :android do
  desc "Build Debug"
  lane :build_debug do
    ionic(
      platform: 'android',
      prod: true,
      release: false
    )
  end
end
```

So no my config.xml is not in the same folder as the platform folder

**Comment by raiden0610** [comment]
I can't do that because fastlane tell me that he didn't detect any android or IOS project

**Comment by janpio** [comment]
Ok, so the `fastlane init` process got dumbed down :(

Just create the `fastlane` folder and `Fastfile` in it manually and try running it.

**Comment by raiden0610** [comment]
Yup in this case it's working 😄 
Kind of misleading with `fastlane init` 😭 
Thanks

**Comment by janpio** [comment]
Great, I created #43 to think about a solution for the initial problem you were having. This is some very special code reading/writing to `config.xml` that porbably would not have been relevant to you anyway, so I am not happy this cause problems for you.

Feel free to ask further questions if you encounter any additional problem! 🎢
