### ISSUE TITLE
Is plugin support Ionic V4 ?

### ISSUE THREAD

**Issue by laurentyhuel** [ionic-zone/fastlane-plugin-ionic#47]
Hello,

Is plugin support Ionic V4 (and monorepo) ?

I have an application with Ionic V4 in monorepo (web + mobile).

In my monorepo, I go to my mobile project folder and run
`fastlane init swift`

> [✔] 🚀 
> [✔] Looking for iOS and Android projects in current directory...
> [17:33:34]: Created new folder './fastlane'.
> [17:33:34]: It looks like there is no iOS project in the current directory, though we did find one in a sub-directory
> [17:33:34]: Please `cd` into the directory of the intended Xcode project you wish to use.
> 
> [!] Please `cd` into the directory of the intended Xcode project you wish to use and run `fastlane init` again

`ls platforms/ios/`
![image](https://user-images.githubusercontent.com/7816190/58266380-d340c000-7d81-11e9-8fc5-b7865b49b89d.png)

`ls platforms/android`
![image](https://user-images.githubusercontent.com/7816190/58266557-2b77c200-7d82-11e9-9762-77b5e593baa5.png)

**Comment by janpio** [comment]
`fastlane init` is a command provided by Fastlane and has nothing to do with this plugin. Fastlane doesn't handle Cordova projects well, so you will have to create the files manually.

Ionic v4 is totally irrelevant to this plugin as well, as it works with Ionic CLI, which then does its thing to the actual Ionic projects. So: Yes, works with Ionic v4.

What this could have to do with monorepo I have no idea.
