### ISSUE TITLE
Command CodeSign failed with a nonzero exit code

### ISSUE THREAD

**Issue by osrl** [ionic-zone/fastlane-plugin-ionic#54]
I'm running `ionic(platform: 'ios')` commant after a `match(type: "appstore")` but I'm getting a very long error message with the following ending:

```
CodeSign /var/root/Library/Developer/Xcode/DerivedData/MyApp-ccztmzoxngbmurbvfmxpessvdbbf/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/InstallationBuildProductsLocation/Applications/MyApp.app (in target: MyApp)
    cd /Users/xcloud/workspace/DCIOSApp_DummApp/platforms/ios
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate

Signing Identity:     "iPhone Distribution: ****"
Provisioning Profile: "match AppStore ***"
                      (****)

    /usr/bin/codesign --force --sign D4DC6C722544727A58C7449A285185812CAD815E --entitlements /var/root/Library/Developer/Xcode/DerivedData/MyApp-ccztmzoxngbmurbvfmxpessvdbbf/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/MyApp.build/Release-iphoneos/MyApp.build/MyApp.app.xcent /var/root/Library/Developer/Xcode/DerivedData/MyApp-ccztmzoxngbmurbvfmxpessvdbbf/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/InstallationBuildProductsLocation/Applications/MyApp.app
/var/root/Library/Developer/Xcode/DerivedData/MyApp-ccztmzoxngbmurbvfmxpessvdbbf/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/InstallationBuildProductsLocation/Applications/MyApp.app: errSecInternalComponent
Command CodeSign failed with a nonzero exit code

** ARCHIVE FAILED **


The following build commands failed:
        CodeSign /var/root/Library/Developer/Xcode/DerivedData/MyApp-ccztmzoxngbmurbvfmxpessvdbbf/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/InstallationBuildProductsLocation/Applications/MyApp.app
(1 failure)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.

        cordova compile ios --release --device --packageType=app-store --developmentTeam... exited with exit code 65.
```

The commant it's trying to run is this:

ionic cordova compile ios --no-interactive --release --device --prod -- --packageType=app-store --developmentTeam=**** --provisioningProfile=***

**Comment by janpio** [comment]
Does anything of the output look wrong to you?
Can you run the command manually and it succeeds?

**Comment by osrl** [comment]
No It doesn't succeed. The error doesn't tell anything about the code signing issue.

**Comment by janpio** [comment]
I assume you did all the things that appear when you google for "errSecInternalComponent
Command CodeSign failed with a nonzero exit code"?

**Comment by osrl** [comment]
Yes thank you for that. It appears it's not related to this plugin, not even ionic. It was a keychain access problem. Build was on a jenkins slave, connected through ssh. If anyone in the future run across the same error, Keychain was already unlocked (I've unlocked it using terminal) but it didn't work. I had to lock it and unlock it through keychain access app. I ran the build command in terminal app (not ssh), it asked me to allow something, I clicked always allow. And it worked afterwards.

**Comment by janpio** [comment]
Awesome that it works for you now. I hate these permission errors, almost impossible to debug and you never know if you really, actually resolved it.

**Comment by omar300** [comment]
> Yes thank you for that. It appears it's not related to this plugin, not even ionic. It was a keychain access problem. Build was on a jenkins slave, connected through ssh. If anyone in the future run across the same error, Keychain was already unlocked (I've unlocked it using terminal) but it didn't work. I had to lock it and unlock it through keychain access app. I ran the build command in terminal app (not ssh), it asked me to allow something, I clicked always allow. And it worked afterwards.

Hey! can you please guide how you locked it via keychain app? i am unable to find anything relatable to VS code in keychain.. thanks

**Comment by osrl** [comment]
Hi @omar300 . Screenshot is from keychain app.
![Screen Shot 2020-02-17 at 18 30 11](https://user-images.githubusercontent.com/781453/74667024-9cce8f00-51b3-11ea-84e0-5c68ade6b8f9.png)
