### ISSUE TITLE
How to upload to testflight?

### ISSUE THREAD

**Issue by prescindivel** [ionic-zone/fastlane-plugin-ionic#55]
I fixed with:

lane :deploy_testflight do
    match(type: "appstore")
    ionic(
      platform: "ios",
      prod: true,
      release: true,
      type: "appstore",
    )
    testflight(
      ipa: ENV["CORDOVA_IOS_RELEASE_BUILD_PATH"],
      skip_waiting_for_build_processing: true,
    )
  end

**Comment by janpio** [comment]
Yep, that looks perfectly fine.
